version: "3.9"
services:
  # web:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/tmp/nginx.conf
  #   environment: 
  #     - FLASK_SERVER_ADDR=backend:9091  
  #   command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  web:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/code
        depends_on:
            - mongo
  mongo:
        image: mongo
  # redis:
  #       image: redis
  # backend:
  #   build: flask
  #   environment: 
  #     - FLASK_SERVER_PORT=9091
  #   volumes:
  #     - ./backend:/src
  #   depends_on:
  #     -  elasticsearch  
  # elasticsearch:
  #   image: elasticsearch:7.8.0
  #   container_name: es
  #   environment:
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - elastic